const LABELS = [
    'Product Update',
    'New Product',
    'New Feature',
    'Technical Issue',
    'Cybersecurity Breach',
    'Leadership Change',
    'Layoffs',
    'Hiring',
    'Earnings Report',
    'Merger/Acquisition',
    'Funding',
    'Regulatory Approval',
    'Legal issue',
    'Scandal',
    'Customer Issue',
    'Philanthropy',
    'Market Expansion',
    'Pricing Change',
    'Partnership/Collaboration',
    'Product Sunset/Deprecation',
    'Security Vulnerability',
    'Data Privacy',
    'Outage/Service Disruption',
    'Feature Rollout',
    'Platform Support/Compatibility',
    'Executive Interview/Statement',
    'IPO/SPAC',
    'Stock Movement',
    'Geographic Expansion',
    'Sustainability/ESG',
    'Awards/Recognition',
    'Conference/Event Announcement',
    'Patent/Intellectual Property',
    'Analyst Rating/Upgrade',
    'other'
]

export default LABELS